# -*- coding: utf-8 -*-
"""20230913_A120E101.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T7Yjpdis9FBEQTB9mMGnzdGccA1ruUQX
"""

3**2